const DummyData = [
{
    backSeat: 1,
    carColor: "Red",
    carPlate: "ABC123",
    carType: "Sedan",
    endingPoint: "Ending Location 1",
    loggage: 0,
    pet: 1,
    price: 20,
    reservationDate: "2023-12-07",
    reservationTime: "12:00 PM",
    ride_id: 1,
    seatsAv: 3,
    seatsBooked: 2,
    smoking: 0,
    startingPoint: "Starting Location 1",
    user_id: 1,
  },
  {
    backSeat: 4,
    carColor: "Blue",
    carPlate: "XYZ789",
    carType: "SUV",
    endingPoint: "Destination 2",
    loggage: 1,
    pet: 0,
    price: 25,
    reservationDate: "2023-12-08",
    reservationTime: "3:30 PM",
    ride_id: 2,
    seatsAv: 4,
    seatsBooked: 1,
    smoking: 1,
    startingPoint: "Departure Location 2",
    user_id: 2,
  },
]
export default DummyData
